create user  `MANAGER_USER`@`localhost` IDENTIFIED BY `fjeclot`;
GRANT ALL PRIVILEGES ON MANAGER.* TO `MANAGER_USER`@`localhost` 


CREATE DATABASE IF NOT EXISTS MANAGER;
USE MANAGER;
CREATE TABLE IF NOT EXISTS PRODUCTS (
	ID INT(8) AUTO_INCREMENT PRIMARY KEY,
	NAME TEXT(50),
	PRICE DECIMAL(10,2)
);
CREATE TABLE IF NOT EXISTS CUSTOMERS (
	ID INT(8) AUTO_INCREMENT PRIMARY KEY,
	NAME TEXT(50) NOT NULL,
	SURNAME_1 TEXT(50) NOT NULL,
	SURNAME_2 TEXT(50) DEFAULT NULL,
	POSTAL_ADRESS TEXT NOT NULL,
	POSTAL_CODE INT(8) NOT NULL,
	TOWN TEXT(50) NOT NULL,
	PROVINCE TEXT(50) NOT NULL,
	TELEPHONE INT(16) DEFAULT NULL,
	FAX INT(16) DEFAULT NULL,
	EMAIL TEXT(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS INVOICE (
	ID INT(8) AUTO_INCREMENT PRIMARY KEY,
	CUST_ID INT(8) NOT NULL,
	DATE DATETIME,
	DISCOUNT INT(8) DEFAULT 0,
	VAT INT(8) DEFAULT 21,
	FOREIGN KEY(CUST_ID) REFERENCES CUSTOMERS(ID),
	CONSTRAINT CHK_DISCOUNT CHECK (DISCOUNT BETWEEN 0 AND 100),
	CONSTRAINT CHK_VAT CHECK (VAT BETWEEN 0 AND 100)
);
CREATE TABLE IF NOT EXISTS INV_DETAIL (
	INV_ID INT(8) AUTO_INCREMENT,
	PROD_ID INT(8) NOT NULL,
	QUANTITY INT(8),
	PRIMARY KEY(INV_ID, PROD_ID),
	FOREIGN KEY(PROD_ID) REFERENCES PRODUCTS(ID),
	FOREIGN KEY(INV_ID) REFERENCES INVOICE(ID)
);

